# Generated by Django 5.1.3 on 2024-11-09 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=20, unique=True)),
                ('trailer_type', models.CharField(max_length=50)),
                ('assembly_date', models.DateField()),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('ready', 'Готов к отгрузке'), ('shipped', 'Отгружен')], default='in_progress', max_length=20)),
                ('order_date', models.DateField()),
                ('additional_options', models.TextField(blank=True)),
                ('specification', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
        ),
    ]
